name: doorstep
description: "doorstep app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mailer: ^6.4.1
  google_places_flutter: ^2.1.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4
  intl_phone_field: ^3.2.0
  responsive_sizer: ^3.3.1
  easy_localization: ^3.0.7+1
  get: ^4.7.2
  cached_network_image: ^3.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png
    - assets/plumber.png
    - assets/home.png
    - assets/

flutter_launcher_icons:  
  android: true
  ios: true
  image_path: "assets/logo1.png"  
  adaptive_icon_background: "#ffffff"  
  adaptive_icon_foreground: "assets/logo1.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo1.png
  android: true
  ios: true
  fullscreen: true
